spring:
  cloud:
    gateway:
      globalcors:  # 全局跨域
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
      routes:
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            # Query
            - name: Query
              args:
                param: q
                regexp: haha
            # 自定义断言工厂
            - Vip=user,lpy
          order: 10
          metadata:
            hello: word
        - id: order-route
          uri: lb://service-order
          predicates:
            # 处理该路径下的所有请求
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/?(?<segment>.*),/$\{segment}      # 路径重写 filter
            - OnceToken=X-Response-Token, uuid
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/$\{segment}     # 路径重写 filter
#            - AddResponseHeader=X-Response-Abc, 123                     # 添加请求头 filter
#        # 断言的第二种写法
#        - id: order-route
#          uri: lb://service-order
#          predicates:
#            - name: Path
#              args:
#                patterns: /api/order/**
#                matchTrailingSlash: true

      default-filters:    # 默认 filter
        - AddResponseHeader=X-Response-Abc, 123                     # 添加请求头 filter
